# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: minjeeki <minjeeki@student.42seoul.kr>     +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2023/10/05 16:17:49 by minjeeki          #+#    #+#              #
#    Updated: 2024/04/30 23:35:21 by minjeeki         ###   ########seoul.kr   #
#                                                                              #
# **************************************************************************** #

CC      = cc
CFLAGS    = -Wall -Wextra -Werror
SRCS    = ft_bzero.c ft_isalnum.c ft_isalpha.c ft_isascii.c \
ft_isdigit.c ft_isprint.c ft_memcpy.c ft_memmove.c ft_memset.c \
ft_strchr.c ft_strlcat.c ft_strlcpy.c ft_strlen.c ft_tolower.c \
ft_toupper.c ft_strrchr.c ft_strncmp.c ft_memchr.c ft_memcmp.c \
ft_strnstr.c ft_atoi.c ft_calloc.c ft_strdup.c ft_substr.c ft_strjoin.c \
ft_strtrim.c ft_split.c ft_itoa.c ft_strmapi.c ft_striteri.c \
ft_putchar_fd.c ft_putstr_fd.c ft_putendl_fd.c ft_putnbr_fd.c
SRCS_B    = ft_lstnew_bonus.c ft_lstadd_front_bonus.c ft_lstsize_bonus.c \
ft_lstlast_bonus.c ft_lstadd_back_bonus.c ft_lstdelone_bonus.c \
ft_lstclear_bonus.c ft_lstiter_bonus.c ft_lstmap_bonus.c
OBJ     = $(SRCS:.c=.o)
OBJ_B     = $(SRCS_B:.c=.o)
NAME    = libft.a

all : $(NAME)

$(NAME): $(OBJ)
	ar rc $(NAME) $^

bonus : LAST_bonus

LAST_bonus : $(OBJ_B)
	ar rc $(NAME) $^
	@touch $@

$(OBJ): $(SRCS)
	$(CC) $(CFLAGS) -c $^

$(OBJ_B): $(SRCS_B)
	$(CC) $(CFLAGS) -c $^

clean:
	rm -f $(OBJ)
	rm -f $(OBJ_B)
	rm -f LAST_bonus

fclean: clean
	rm -f $(NAME)

re: fclean all

.PHONY: bonus all clean fclean re